### ISSUE TITLE
bugs when running simulation.py and simple_simulation.py

### ISSUE THREAD

**Issue by ismirk** [paulvangentcom/python_corona_simulation#3]
When running simulation.py:

Traceback (most recent call last):
  File "simulation.py", line 11, in <module>
    from population import initialize_population, initialize_destination_matrix,\
ImportError: cannot import name 'population_trackers' from 'population' (/Users/ismirkamili/pyprojects/python_corona_simulation/population.py)

When running simple_simulation.py

...
  File "/Users/ismirkamili/pyprojects/python_corona_simulation/env/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 418, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/Users/ismirkamili/pyprojects/python_corona_simulation/env/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 403, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'render/0.png'

Any missing resource or module? I use python 3.7 with venv

Thank you

**Comment by paulvangentcom** [comment]
No you're good. Seems like I branched from master 1 commit late. Give me 10 minutes.

**Comment by paulvangentcom** [comment]
Please delete your local copy and clone again. It should work now.

Keep in mind that there's a major refactor upcoming in the next two days so don't yet build your own functionality unless you don't mind re-writing after
